linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    #- depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - goheader
    - goimports
    # - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck

linters-settings:
  wrapcheck:
    # enable .Propagate as a wrapper function
    ignoreSigs:
      - stacktrace.Propagate(
      - stacktrace.NewError(

issues:
  exclude-rules:
    - path: internal/controller/http
      linters:
        - godot